[package]
name = "module-logger-request"
version = "0.1.0"
authors = ["François Mockers <mockersf@gmail.com>"]

[dependencies]
mini-http = { path = "../mini-http" }
module-interface = { path = "../module-interface" }
