[package]
name = "module-logger-request"
version = "0.1.0"
authors = ["François Mockers <mockersf@gmail.com>"]

[lib]
name = "module_logger_request"
crate-type = ["dylib"]

[dependencies]
hyper = { git = "https://github.com/hyperium/hyper.git" }

module-interface = { path = "../module-interface" }
